name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress || true

      - name: Build app
        run: npm run build --if-present

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy Firestore rules and indexes
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g firebase-tools
          firebase deploy --only firestore:rules,firestore:indexes --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Backup project as zip
        if: github.ref == 'refs/heads/main'
        run: |
          bash backup_baseline.sh
      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-backup
          path: backups/*.zip

      # Ajoute ici des étapes de déploiement si besoin (Firebase, Vercel, etc.) 